// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg44tvFIhcvD_sgNNMcE9BFNeFev5zUgg',
    appId: '1:871180208497:web:b810da7a7890eeecda0ed0',
    messagingSenderId: '871180208497',
    projectId: 'draftshare-3ba2c',
    authDomain: 'draftshare-3ba2c.firebaseapp.com',
    storageBucket: 'draftshare-3ba2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY_fyd0tFeLeqz1KOdAmjELYkL2p9N9pQ',
    appId: '1:871180208497:android:e4913e9e034bafeeda0ed0',
    messagingSenderId: '871180208497',
    projectId: 'draftshare-3ba2c',
    storageBucket: 'draftshare-3ba2c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg44tvFIhcvD_sgNNMcE9BFNeFev5zUgg',
    appId: '1:871180208497:web:3c02e9f3c2dcd8f2da0ed0',
    messagingSenderId: '871180208497',
    projectId: 'draftshare-3ba2c',
    authDomain: 'draftshare-3ba2c.firebaseapp.com',
    storageBucket: 'draftshare-3ba2c.firebasestorage.app',
  );
}
